"""修改管理员用户表名

Revision ID: 48b13229c4d2
Revises: f57c02279ed8
Create Date: 2018-06-19 11:43:36.298255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48b13229c4d2'
down_revision = 'f57c02279ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avatar', sa.String(length=50), nullable=True),
    sa.Column('nick_name', sa.String(length=20), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('isDelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('avatar', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('nick_name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('mobile', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('admin_info')
    # ### end Alembic commands ###
